name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.4+4

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  english_words: ^4.0.0
  provider: ^6.0.0
  # flutter_session: ^0.1.1
  mongo_dart: ^0.8.2
  geolocator: ^9.0.0
  geocoding: ^2.0.5
  http: ^0.13.5
  flutter_login: ^4.1.1
  get: ^4.6.5
  shared_preferences: ^2.0.18
  email_validator: ^2.1.17
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  intl: ^0.18.0
  camera: ^0.10.3+2
  path_provider: ^2.0.13
  flutter_exif_rotation: ^0.5.1
  image_picker: ^0.8.7
  flutter_launcher_icons: ^0.12.0
  http_parser: ^4.0.2
  tuple: ^2.0.1
  google_maps_flutter: ^2.3.0
  location: ^5.0.3
  dropdown_textfield: ^1.0.8
  date_field: ^3.0.5
  baseflow_plugin_template: ^2.1.2
  permission_handler: ^11.0.0
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans/static/OpenSans-Regular.ttf
          - asset: assets/fonts/OpenSans/static/OpenSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/OpenSans/static/OpenSans-Italic.ttf
            style: italic
  assets:
    - assets/
